### ISSUE TITLE
¿Qué es una tarea?

### ISSUE THREAD

**Issue by smallPingu** [AlvaroSanPal95/AssignedOrganization#6]
Para resolver #2, tenemos que determinar que es una tarea antes de abordar qué hacer con ellas.

Asignar atributos específicos para determinar cuales son las características que nos benefician se deben tener en cuenta, para así conseguir una distribución final mejor.

**Comment by smallPingu** [comment]
Para empezar, ¿qué te parecen los atributos "Título, Descripción, Duración, Urgencia"?

**Comment by JJ** [comment]
Este issue es correcto, pero no hay ningún commit que lo mencione. En todo caso, no plantea un problema, porque aparte de enlazar #2, no hay ninguna característica específica tomada de la misma HU que defina o determine qué tiene que ser una tarea.
