### ISSUE TITLE
¿Cómo determinar la urgencia de una tarea?

### ISSUE THREAD

**Issue by smallPingu** [AlvaroSanPal95/AssignedOrganization#7]
Siguiendo la idea de #6, no sabemos como un sistema evalúa la urgencia de una tarea para determinar su prioridad con respecto a otras.

A partir de los atributos de cada tarea, se deberán tener en cuenta varios aspectos para decidir tal parámetro.

**Comment by JJ** [comment]
El problema de crear estos issues en cascada es que se corre el peligro de crear un primero issue de la cascada incorrecto, lo que hace que el resto también lo sean. Tampoco está bien definido qué consideras una tarea, o qué problemas plantea, más allá del nombre. Sería imposible desarrollar a partir de ahí. Como en el caso anterior, tampoco hay ningún commit que apunte a este issue, en todo caso, por lo que lo desarrollado no puede ser correcto.
